// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpfCEJWb7NyMdh6gQw6zll_EJfHK7dfc',
    appId: '1:1079001832756:web:d119375a1336e4f1b11961',
    messagingSenderId: '1079001832756',
    projectId: 'priority-shoesly',
    authDomain: 'priority-shoesly.firebaseapp.com',
    storageBucket: 'priority-shoesly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOsjvMykiMyHMqLenxrQ7cNtSsWACZRR4',
    appId: '1:1079001832756:android:f89477b1fc1746dbb11961',
    messagingSenderId: '1079001832756',
    projectId: 'priority-shoesly',
    storageBucket: 'priority-shoesly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhZYfSbk4nxQCAhqVx06RV-yDDh6Ct9R0',
    appId: '1:1079001832756:ios:7129802c2cd568a6b11961',
    messagingSenderId: '1079001832756',
    projectId: 'priority-shoesly',
    storageBucket: 'priority-shoesly.appspot.com',
    iosBundleId: 'com.saurav.shoesly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhZYfSbk4nxQCAhqVx06RV-yDDh6Ct9R0',
    appId: '1:1079001832756:ios:7129802c2cd568a6b11961',
    messagingSenderId: '1079001832756',
    projectId: 'priority-shoesly',
    storageBucket: 'priority-shoesly.appspot.com',
    iosBundleId: 'com.saurav.shoesly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZpfCEJWb7NyMdh6gQw6zll_EJfHK7dfc',
    appId: '1:1079001832756:web:1eb7ee7a515b28e2b11961',
    messagingSenderId: '1079001832756',
    projectId: 'priority-shoesly',
    authDomain: 'priority-shoesly.firebaseapp.com',
    storageBucket: 'priority-shoesly.appspot.com',
  );
}
